### ISSUE TITLE
New README

### ISSUE THREAD

**Issue by Kronifer** [cat-dev-group/bot#1]
@dawnofmidnight I believe you have the power to do this, just add a quick bot description

**Comment by dawnofmidnight** [comment]
Give me the words, I shall edit.

**Comment by Kronifer** [comment]
You have been assigned

**Comment by dawnofmidnight** [comment]
If you're writing it, just open the first ever pr.

**Comment by dawnofmidnight** [comment]
Crap, wrong button. I'm bad at this
