### ISSUE TITLE
Add an embed command.

### ISSUE THREAD

**Issue by dawnofmidnight** [cat-dev-group/bot#10]
Add a command that generates embeds using either JSON parsing, direct python code, or an interactive setup. I think this should probably be locked to Cat Devs.

This would be useful because it would allow us to see how embeds look before we try committing them many times.

Anyone could implement this.

**Comment by Kronifer** [comment]
I think this is something that could be done, approved

**Comment by dannynotsmart** [comment]
yes, good idea. 
we could use self.bot.wait_for, which is my idea

**Comment by dannynotsmart** [comment]
if not, we could specify the arguments with quotation marks or something

**Comment by Kronifer** [comment]
@dannynotsmart youve been assigned, it looks good so far

**Comment by dannynotsmart** [comment]
ok, got it. i'll start working on the code tmr if i can
