### ISSUE TITLE
Catification

### ISSUE THREAD

**Issue by Objectivitix** [cat-dev-group/bot#12]
# Desc
As our cat mascot for catlang, it is absolutely imperative-necessary-obligatory-essential and every other synonym of those four words ever to implement `.catify`, our first ever project as a team. This will require two simple steps of implementation:

# Implementation
1. put cats in constants.py
2. copy the catify code into a catify file, in exts

**Comment by hypergamer80** [comment]
cat devs, please tell me your suggestions and ideas. thanks

**Comment by Kronifer** [comment]
Let's ~~copy~~ borrow the one I made for pydis

**Comment by hypergamer80** [comment]
**WE** made, but yes that is the central idea. We copy it (although i'm not sure what are the legal effects of this. is sir lancebot licensed?)

but that shouldn't matter, since we made the code... right?

**Comment by Kronifer** [comment]
Sir lancebot is open source, we can use it

**Comment by Kronifer** [comment]
And yes, **WE** made, I'm an idiot 🥴

**Comment by Kronifer** [comment]
Approved

**Comment by Objectivitix** [comment]
already implemented, closed.
