### ISSUE TITLE
Add error handling

### ISSUE THREAD

**Issue by Kronifer** [cat-dev-group/bot#13]
Right now, we have none. So, it looks like shit when our commands don't work. Let's fix that! I propose we take a similar route to pydis, with negative replies and embeds and stuff

**Comment by hypergamer80** [comment]
I very much agree. Although our error text shouldn't be as formal as pydis, since we're centered around cats and informality (add some memes?).

**Comment by Kronifer** [comment]
I'll get on this later

**Comment by VirdanTheBurden** [comment]
I can do a once over and built a list of commands that need error handling. I'll get back to this thread soon.
