### ISSUE TITLE
Integrate pulling from config.yml

### ISSUE THREAD

**Issue by Kronifer** [cat-dev-group/bot#14]
We currently have our config.yml, but most of us manually pull from it. I suggest we work on either pulling from the yml into constants or get red of constants and change to the config file entirely.

**Comment by dawnofmidnight** [comment]
I can set up a function that allows us to do something like `yaml(guild.role.cat_devs)`

**Comment by Kronifer** [comment]
That sounds good, would you be willing to take this on?

**Comment by dawnofmidnight** [comment]
Yes, I can do that.
