### ISSUE TITLE
Pull config vals into constants.py

### ISSUE THREAD

**Issue by Objectivitix** [cat-dev-group/bot#31]
Currently, we have some constants in config.yml and constants.py, and our code is importing values from both. This is not optimal for clean, sustainable, and maintainable code (and is also unintuitive for people wanting to contribute), and I propose that we use Squid's helper func to pull constants from config into constants.py, then import all constants from there.

**Comment by dawnofmidnight** [comment]
I agree

**Comment by Objectivitix** [comment]
hmm we got some debate

i quote Squid - @VirdanTheBurden:
"All constant values should be serialized in a file that explains their purpose. For example, `config.yml` should contain constants that relate to configuration. That is my only gripe. Moving the yaml-parser somewhere else is fine; that's just changing an import statement. But do not store constant values in a non-serialized file, like a `py` file."

**Comment by Objectivitix** [comment]
it has been decided upon. constants,py will be deleted
