### ISSUE TITLE
Make a command that sends the contents of our YAML file

### ISSUE THREAD

**Issue by dannynotsmart** [cat-dev-group/bot#53]
I feel this is good if we want to see what's in our yaml file. For example, if we wonder what colors are there, we can run a command that checks the colors in the yaml. Or, if we want to see responses, etc etc.

**Comment by Kronifer** [comment]
Before we do this, we need to confirm the yaml file doesn't confirm any sensitive info

**Comment by Kronifer** [comment]
We could just as easily send a link to the yaml file to prevent large messages

**Comment by dawnofmidnight** [comment]
> Before we do this, we need to confirm the yaml file doesn't confirm any sensitive info

It does not

**Comment by Kronifer** [comment]
Im denying this, i dont see a need for it.
