### ISSUE TITLE
[feature] Send dm to the user that gets infracted.

### ISSUE THREAD

**Issue by AnkithAbhayan** [cat-dev-group/bot#66]
**What is the feature you want to add?**
Whenever a user gets an infraction like a ban or a mute, a DM embed can be sent by the bot to the person who got infracted highlighting some useful information.

**Describe the solution you'd like**
An embed sent to the infracted user containing information. The one below is just an example
![image](https://user-images.githubusercontent.com/69845955/117433859-97d93500-af49-11eb-865e-7489aaf65f48.png)
This needn't be the case, more Info like, infraction type, reason for infraction, infraction until what time period, and a link to the server rules (like the example of python discord) can be specified. 

**Describe alternatives you've considered**
I've considered no alternatives but my proposed solution hopefully would do the job just fine. In my opinion something like this is really necessary since I got muted before for spamming embeds but I had no idea why I got muted until I checked the mod logs which not everyone has access to. 

**Would you like to implement this?**
yes!

**Comment by Kronifer** [comment]
I'll approve it, but we need one more approval first

**Comment by AnkithAbhayan** [comment]
umm... so it's disapproved? Or did people not see this issue yet? 
I'd really appreciate a response from others disapproving or approving, thankyou :D

**Comment by dawnofmidnight** [comment]
I like the idea;

**Comment by Kronifer** [comment]
@AnkithAbhayan thats approved then!

**Comment by AnkithAbhayan** [comment]
nvm.

**Comment by dawnofmidnight** [comment]
> How can I link pull requests that auto closes an issue when it gets merged?

Just type: "Closes #issue" at the top
